    version: '3.8'
    services:
      db:
        image: postgres:latest
        container_name: postgres_tickets_db
        restart: unless-stopped
        environment:
          POSTGRES_DB: tickets
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - "5432:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data

    volumes:
      pgdata: